#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 79f86e8b-c982-4f43-8430-e5131c604b58
# Source File: Removing Items from Lists Using the Keyboard.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
Cg4AAB+LCAAAAAAABADlV11v2jAUfZ+0/2D5OSKEjwJSiLTBqqFVawW03Rtykhvw5tjINtDs18/5
oE2BAe0KD6uQEDHn3nvOuXGu4w4hEEuQSZ9ogswPRQXv4hr2Pn5AyL2WdEo5YZeUwXcSgzeEWCwp
n6KBhlihSIoYXVGlFbpV6bKeAfoGiS+IDCtzFbn2Voo8sf8TAo10MocuHiXKZKvcUx6KlapcChnn
3xba9ZeF7gqejUo1/Viot2B6IaHLYaElYRa6WfiMBobJWPwC3vVbLdIMmhdOp96AaruDETdUujgy
+RyMghlloTQ43BNcS8FUrt8QvZFiDlInRUCPUeB6RH8D9mrthoVqF45rr0F/CUplYy+rdRA7hgeN
vVTnNvSwaWkr7iisTm4cU7qwap97O/wTbBHzEsBA0ltpn6g85iuQEOTphJUYGU5DiMBICqDgHWQc
ZhkHc8PYZf52KuBJ8Wbbtk3I9s6LLFj3NcWdy4IBV5oYB/qgAknnWshNU3Iek4LHJOMxKVOd7Lfq
PxZee6/C6+9VeONfnwpXIiDaqMJevW2heuOIkHywPD2LjwjJR5fTqVnIabeOCBgTf8BDeMBe9Qj0
rYKeiOdGiM9gpImGQUym8BlmZEmFNJONMAVHJEp9xV4fNKFM7cJ/WZpBXIBNn/tixctWTIo1186A
6xFq5zM0P4Q8uzg8XM8zh3YOnL2HhZzRwZPFPQ31zLS+fbEBfe7DJ6UgNhRBrfMUK4kXq0BIRv03
kOnaj1k3q+TGnqPGmzfvcMX0mH2eQpKszIH8NbWq9agZtSLHCZtVUieHa/2I2Xk0UWluUyGTEcgl
DeBVLXuxup6QcBZ5hSqzN420E2h7vMz3tmuX3/28PyHSxDcKDgAA#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.99
     Generated on:       23-12-2015 11:40
     Generated by:        
     Organization:        
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2015
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-Removing_Items_from_Lists_Using_the_Keyboard_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$lstControl = New-Object 'System.Windows.Forms.ListView'
	$columnheader1 = New-Object 'System.Windows.Forms.ColumnHeader'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	$lstControl_KeyDown = [System.Windows.Forms.KeyEventHandler]{
	    If ($_.KeyCode -eq [System.Windows.Forms.Keys]::Delete)
	    {
	        $text = $lstControl.SelectedItems[0].SubItems[0].Text
	        ForEach ($item in $lstControl.SelectedItems)
	        {
	            $lstControl.Items.Remove($item)
	        }
	    }
	}
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$lstControl.remove_KeyDown($lstControl_KeyDown)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($lstControl)
	$form1.ClientSize = '284, 261'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	#
	# lstControl
	#
	[void]$lstControl.Columns.Add($columnheader1)
	$System_Windows_Forms_ListViewItem_1 = New-Object 'System.Windows.Forms.ListViewItem' ('1')
	[void]$lstControl.Items.Add($System_Windows_Forms_ListViewItem_1)
	$System_Windows_Forms_ListViewItem_2 = New-Object 'System.Windows.Forms.ListViewItem' ('2')
	[void]$lstControl.Items.Add($System_Windows_Forms_ListViewItem_2)
	$System_Windows_Forms_ListViewItem_3 = New-Object 'System.Windows.Forms.ListViewItem' ('3')
	[void]$lstControl.Items.Add($System_Windows_Forms_ListViewItem_3)
	$System_Windows_Forms_ListViewItem_4 = New-Object 'System.Windows.Forms.ListViewItem' ('4')
	[void]$lstControl.Items.Add($System_Windows_Forms_ListViewItem_4)
	$lstControl.Location = '38, 34'
	$lstControl.Name = 'lstControl'
	$lstControl.Size = '192, 187'
	$lstControl.TabIndex = 0
	$lstControl.UseCompatibleStateImageBehavior = $False
	$lstControl.View = 'Details'
	$lstControl.add_KeyDown($lstControl_KeyDown)
	#
	# columnheader1
	#
	$columnheader1.Text = 'Header'
	$columnheader1.Width = 186
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Call-Removing_Items_from_Lists_Using_the_Keyboard_psf | Out-Null
